# Generated by Django 5.2 on 2025-04-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talaba',
            options={'ordering': ['ism', 'guruh'], 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterUniqueTogether(
            name='talaba',
            unique_together={('ism', 'guruh')},
        ),
    ]
